name: Maven CI/CD

on:
  push:
    branches: [ main ]
  
jobs:
  
  
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}

  test-docker-image:
    name: Test docker image with curl
    runs-on: ubuntu-latest
    needs: [build-docker-image]

    steps:
      - uses: actions/checkout@v2
      - name: Run docker image
        run: docker run -d --name products-service-example "APP_ARGS=http://127.0.0.1:8080 http://127.0.0.1:8080 http://127.0.0.1:8080" -p 8080:8080 ${{ secrets.DOCKER_REPO }}:latest
      - name: Build Container image
        run: curl http://localhost:8080/123
     
