name: Release workflow

on:
  push:
    branches: 
      - staging

jobs:
  release:        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0	
        with:        
            github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:          
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
            
      - name: "Release - Trigger Telegram alert"
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} / [ ${{ github.repository }} ]

            ✨ New release! - ${{ steps.tag_version.outputs.new_tag }} ✨

            Changelog:
            ${{ steps.tag_version.outputs.changelog }}

            See full details at:
            ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.tag_version.outputs.new_tag }}

  automatic-merge:
      name: Automatic merge
      runs-on: ubuntu-latest
      needs: [ release ]
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2                              
            
        - name: repo-sync
          uses: repo-sync/github-sync@v2
          with:
            source_repo: ${{ github.repository }}
            source_branch: staging
            destination_branch: main
            github_token: ${{ secrets.GITHUB_TOKEN }}
